---
- name: copy file
    copy:
      src: /etc/hosts
      dest: /etc/hosts
      owner: root
      mode: 0644

- name: change hostname
    shell: |-
      hostnamectl set-hostname {{ hostvars[inventory_hostname] }} 

- name: SELinux permissive
    selinux:
      policy: targeted
      state: permissive
