---
# tasks file for pre task for installing OpenStack
#https://docs.ansible.com/ansible/authorized_key_module.html

- name: deploy pub key
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '{{ ansible_env.HOME }}/.ssh/id_rsa.pub') }}"
  register: output
- debug:
    msg: "{{ output }}"

- name: change hostname
  shell: |-
    hostnamectl set-hostname {{ inventory_hostname }}
  register: hostnameoutput
- debug:
    msg: "{{ hostnameoutput }}"

- name: SELinux permissive
  selinux:
    policy: targeted
    state: permissive
    
#- name: change network ifcfg
#  shell: |-
#    nmcli c modify ens35 ipv4.addresses {{ hostvars.ansible_host }}/24 
#    nmcli c down ens35
#    nmcli c up ens35
    
#- name: firewalld
#  shell: |-
#    firewall-cmd --zone=public --add-port=123/udp --permanent
#    firewall-cmd --reload
#    
#    FirewallD is not running
# tasks file for install
- name: yum install repo
  yum:
    name: "{{ pre }}"
    state: latest
  with_items:
      - yum-utils
      - yum-plugin-priorities
      - epel-release
#       - centos-release-openstack-rocky
#       - https://repos.fedorapeople.org/repos/openstack/openstack-rocky/rdo-release-rocky-0.noarch.rpm
      - centos-release-openstack-queens
      - https://repos.fedorapeople.org/repos/openstack/openstack-queens/rdo-release-queens-1.noarch.rpm
  loop_control:
    loop_var: pre
  when: not ansible_check_mode
    
- name: yum install packstack
  yum:
    name:
      - openstack-packstack
      - openstack-utils
      - openstack-heat-*
      - python-heatclient
      - openstack-magnum-api
      - openstack-magnum-common
      - openstack-magnum-conductor
      - openstack-magnum-ui
      - openstack-magnum-doc
  when: not ansible_check_mode

- name: Stop NetworkManager
  systemd:
    state: stopped
    name: NetworkManager

- name: disable service NetworkManager
  systemd:
    name: NetworkManager
    enabled: no

- name: Restart network
  systemd:
    state: restarted
    name: network
