---
# tasks file for pre task for installing OpenStack
#https://docs.ansible.com/ansible/authorized_key_module.html

- name: deploy pub key
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '{{ ansible_env.HOME }}/.ssh/id_rsa.pub') }}"
  register: output
- debug:
    msg: "{{ output }}"

- name: change hostname
  shell: |-
    hostnamectl set-hostname {{ inventory_hostname }}
  register: hostnameoutput
- debug:
    msg: "{{ hostnameoutput }}"

- name: SELinux permissive
  selinux:
    policy: targeted
    state: permissive
    
- name: change network ifcfg
  shell: |-
    nmcli c modify enp0s9 ipv4.addresses {{ hostvars.ansible_host }}/24 
    nmcli c down enp0s9
    nmcli c up enp0s9
    
#- name: firewalld
#  shell: |-
#    firewall-cmd --zone=public --add-port=123/udp --permanent
#    firewall-cmd --reload
#    
#    FirewallD is not running

