---
# tasks file for install
- name: kube config file directory
  file: path=$HOME/.kube state=directory owner=root group=root mode=0755

- name: copy a kubernetes repo
  copy:
    src: "{{ role_path }}/files/kubelet.j2"
    dest: /etc/sysconfig/kubelet
    mode: 0644

#--apiserver-advertise-address=10.0.2.6 --apiserver-cert-extra-sans=10.0.2.6 --node-name k8s000 
- name: kubeadm
  shell: |-
    kubeadm init --pod-network-cidr=10.244.0.0/16
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config
    echo "export KUBECONFIG=/etc/kubernetes/admin.conf" >> ${HOME}/.bash_profile
    source ${HOME}/.bash_profile
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  register: install
- debug: var=install.stdout_lines
