---
# tasks file for ntp
- name: set hostname
  become: true
  hostname: 
    name: ntp001.shift

- name: install ntp
  yum:
    name: ntp
    state: latest

- name: copy a ntp.conf
  copy:
    src: "{{ role_path }}/files/ntp.conf"
    dest: "/etc/ntp.conf"
    mode: 0644
    owner: root
    group: root
  notify:
    - Start ntpd

- name: firewalld
  firewalld:
    service: ntp
    permanent: yes
    state: enabled
    immediate: yes

- name: enable service ntpd and ensure it is not masked
  systemd:
    name: ntpd
    enabled: yes

- name: Make sure a service is running
  systemd:
    state: started
    name: ntpd
