---
# tasks file for showkubeinfos

- name: show kubeinfos
  shell: |-
    kubeadm token list
    #kubeadm token create
    #kubeadm token create --print-join-command
    #kubectl taint nodes --all node-role.kubernetes.io/master-
    kubectl get pods --all-namespaces -o wide
  register: showkubeinfos
- debug: var=showkubeinfos.stdout_lines
