---
# tasks file for masternode
#https://docs.ansible.com/ansible/latest/modules/user_module.html
- name: Create a 2048-bit SSH key for root
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  register: output
- debug:
    msg: "{{ output }}"
