---
# tasks file for install

- name: device-mapper-persistent-data
  yum:
    name:
      - device-mapper-persistent-data

- name: lvm2
  yum:
    name:
      - lvm2

- name: doker
  yum:
    name:
      - docker-ce

- name: install kubes
  shell: |-
    yum -y install --nogpgcheck cri-o
    yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
    sysctl --system

