---
- name: Internal config hosts
  hosts: all
#  gather_facts: False
  roles:
     - config_hosts

- name: config_network
  hosts: nodes
  roles:
     - config_network

- name: add_repo
  hosts: nodes
  roles:
     - add_repo.d

- name: install
  hosts: nodes
  roles:
     - install

- name: install
  hosts: nodes
  roles:
     - exec_kubeadm_init

- name: servicectls
  hosts: masternode
  roles:
     - servicectls

