all:
  hosts:
    node1:
      ansible_host: 10.0.2.8
      ip: 10.0.2.6
      access_ip: 10.0.2.8
    node2:
      ansible_host: 10.0.2.8
      ip: 10.0.2.8
      access_ip: 10.0.2.8
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
