---
#- name: packstack install
#  shell: |-
#    packstack --install-host={{ item.multinode }}

- name: install pexpect
  pip:
    name: pexpect
  become: yes

- name: packstack answer configuration
  expect:
    command: packstack --answer-file={{ role_path }}/files/answer.cfg
    responses:
      "root@.* password.": "{{ all_root_passwd }}"
  register: asnwer
- debug: var=answer.stdout_lines

- name: add br-ex to neutron ini
  shell: |-
    sed -i -e 's/After=network-pre.target ovsdb-server.service ovs-vswitchd.service/After=network-pre.target ovsdb-server.service ovs-vswitchd.service NetworkManager.service/g' /usr/lib/systemd/system/openvswitch.service
    sed -i -e 's/#external_network_bridge =/external_network_bridge = br-ex/g' /etc/neutron/l3_agent.ini
