---
# tasks file for setting_network
    
#- name: change network ifcfg
#  shell: |-
#    nmcli c modify ens35 ipv4.addresses {{ hostvars.ansible_host }}/24 
#    nmcli c down ens35
#    nmcli c up ens35
    
#- name: firewalld
#  shell: |-
#    firewall-cmd --zone=public --add-port=123/udp --permanent
#    firewall-cmd --reload
#    
#    FirewallD is not running
# tasks file for install
- name: Stop NetworkManager
  systemd:
    state: stopped
    name: NetworkManager

- name: disable service NetworkManager
  systemd:
    name: NetworkManager
    enabled: no

- name: Restart network
  systemd:
    state: restarted
    name: network
