---
- name: Internal config hosts
  hosts: repository
  gather_facts: False
  roles:
     - config_hosts

#- name: ntp
#  hosts: gateway
#  strategy: debug
#  roles:
#     - ntp

#- name: gateway setup
#  hosts: gateway
#  roles:
#     - ntp
#     - dns

#- name: pre task for installing OpenStack
#  hosts: external
#  roles:
#     - pre_task_for_installing_OpenStack

- name: setting_network
  hosts: repository
  roles:
     - setting_network

- name: yum
  hosts: repository
  roles:
     - yum

#- name: install_openstack
#  hosts: nodes
#  roles:
#     - install_openstack

#- name: create_SSHkey_for_root
#  hosts: masternode
#  roles:
#     - create_SSHkey_for_root

#- name: openstack install
#  hosts: masternode
#  strategy: debug
#  roles:
#     - install
